image: clojure:lein

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -v -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test-run:
  stage: deploy
  script:
    - lein run ci-cd-mode $TOKEN